### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by J3rryScotty** [wegank/HJWords#1]
Hello Weijia, sorry if contact you here but i haven't found any solutions.
I've seen 2 years ago a good algorithm of a program written in C, i remember, that you've removed..
Now i'm an Computer Engineering student so now i can understand the code, is it possibile to have for studying purpose? Nothing for profit only studying! 
Can you give me your email, telegram? what you want :)
Have a nice day!

**Comment by wegank** [comment]
Since I've removed tons of repositories, I guess you're talking about claymore. No, I did not save a copy of the code, but I believe the algorithm was available in other repositories. You might be interested in [this implementation](https://github.com/mrpeardotnet/WinProdKeyFinder/blob/master/WinProdKeyFind/KeyDecoder.cs), for example.
